[book]
authors = ["Kyle Schreiber"]
language = "en"
multilingual = false
src = "docs"
title = "Kestrel Documentation"

[build]
build-dir = "public/docs"

[output.html]
preferred-dark-theme = "ayu"
site-url = "/docs/"
